require 'yoti'

require_relative 'doc_scan/client'
require_relative 'doc_scan/request/task_results'
require_relative 'doc_scan/request/check_reports'
require_relative 'doc_scan/request/response_config'
require_relative 'doc_scan/request/breakdown'
require_relative 'doc_scan/request/recommendation'
require_relative 'doc_scan/request/detail'
require_relative 'doc_scan/request/check'
require_relative 'doc_scan/request/document_check'
require_relative 'doc_scan/request/document_authenticity_check'
require_relative 'doc_scan/request/document_face_match_check'
require_relative 'doc_scan/request/document_text_data_check'
require_relative 'doc_scan/request/document_text_data_extraction_task'
require_relative 'doc_scan/request/liveness_check'
require_relative 'doc_scan/request/zoom_liveness_check'
require_relative 'doc_scan/request/document_filter'
