require_relative 'doc_scan/request/breakdown'
require_relative 'doc_scan/request/recommendation'
require_relative 'doc_scan/request/detail'
require_relative 'doc_scan/request/check'
require_relative 'doc_scan/request/document_check'
require_relative 'doc_scan/request/document_authenticity_check'
require_relative 'doc_scan/request/document_filter'
