# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cucumber', '~> 4.0'
gem 'dotenv', '~> 2.5'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.8'
gem 'selenium-webdriver', '~> 3.142'
gem 'yoti_sandbox', path: '../..'
